# Generated by Django 6.0.2 on 2026-05-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowforhumanreview',
            name='email_body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
