# Generated by Django 6.0.2 on 2026-05-25 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0008_agentexecution_scraped_data_from_competitor_websites_and_more'),
        ('workflows', '0002_workflowforhumanreview_email_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowforhumanreview',
            name='agent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agent.agent'),
        ),
    ]
