# Generated by Django 6.0.2 on 2026-05-27 10:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0008_agentexecution_scraped_data_from_competitor_websites_and_more'),
        ('workflows', '0004_remove_workflowforhumanreview_agent_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowforhumanreview',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agent.agent'),
        ),
        migrations.AlterField(
            model_name='workflowforhumanreview',
            name='reply_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workflowforhumanreview',
            name='reply_subject',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AttachmentWithHumanReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attachment', models.FileField(upload_to='attachment_for_human_review/')),
                ('human_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='workflows.workflowforhumanreview')),
            ],
        ),
    ]
