# Generated by Django 6.0.2 on 2026-06-11 10:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0010_builtinagent_capabilities_builtinagent_tools'),
        ('workflows', '0009_alter_workflowforhumanreview_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailExecutionResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_id', models.CharField(max_length=255)),
                ('result', models.CharField(choices=[('AUTO_RESOLVED', 'Auto Resolved'), ('HUMAN_REVIEW', 'Human Review'), ('SKIPPED', 'Skipped'), ('FAILED', 'Failed')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_results', to='agent.agent')),
                ('workflow_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='workflows.workflowexecution')),
            ],
        ),
    ]
