# Generated by Django 6.0.2 on 2026-06-25 12:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0013_dailyaiusagesnapshot_aiusagelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=10)),
                ('file_path', models.CharField(blank=True, max_length=512)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=250)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('raw_text', models.TextField(blank=True, null=True)),
                ('resume_analysis', models.JSONField(blank=True, null=True)),
                ('skill_evaluation', models.JSONField(blank=True, null=True)),
                ('ats_score', models.JSONField(blank=True, null=True)),
                ('feedback_report', models.JSONField(blank=True, null=True)),
                ('workflow_execution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume_analyze_execution', to='workflows.workflowexecution')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
