# Generated by Django 6.0.2 on 2026-05-19 09:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPersona',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(choices=[('freelancer', 'Freelancer'), ('business_owner', 'Business Owner'), ('developer', 'Developer'), ('designer', 'Designer'), ('marketer', 'Marketer'), ('student', 'Student'), ('other', 'Other')], default='other', max_length=100)),
                ('industry', models.CharField(blank=True, max_length=255, null=True)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('primary_goals', models.TextField(blank=True, null=True)),
                ('business_description', models.TextField(blank=True, null=True)),
                ('ai_tone', models.CharField(choices=[('formal', 'Formal'), ('casual', 'Casual'), ('friendly', 'Friendly'), ('professional', 'Professional')], default='professional', max_length=50)),
                ('response_style', models.CharField(choices=[('concise', 'Concise'), ('detailed', 'Detailed')], default='detailed', max_length=50)),
                ('ai_priority', models.CharField(choices=[('speed', 'Speed'), ('accuracy', 'Accuracy'), ('balanced', 'Balanced')], default='balanced', max_length=50)),
                ('ai_avoidances', models.TextField(blank=True, null=True)),
                ('communication_style', models.TextField(blank=True, null=True)),
                ('common_messages', models.TextField(blank=True, null=True)),
                ('manages_projects', models.BooleanField(default=False)),
                ('workday_improvements', models.TextField(blank=True, null=True)),
                ('important_documents', models.TextField(blank=True, null=True)),
                ('brand_guidelines', models.TextField(blank=True, null=True)),
                ('long_term_memory', models.TextField(blank=True, null=True)),
                ('privacy_preferences', models.TextField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('completion_percentage', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='persona', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
