# Generated by Django 6.0.2 on 2026-05-20 20:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent', '0004_agentdocuments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('trigger_type', models.CharField(choices=[('manual', 'Manual'), ('event', 'Event'), ('schedule', 'Scheduled')], max_length=500)),
                ('trigger_config', models.JSONField(default=dict)),
                ('prompt_template', models.TextField(blank=True, default='', null=True)),
                ('schedule', models.CharField(blank=True, max_length=250, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('config', models.JSONField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='agent.agent')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowForHumanReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('human_choice', models.CharField(choices=[('pending', 'Pending'), ('accept', 'Accept'), ('reject', 'Reject')], default='pending', max_length=100)),
                ('reply_body', models.TextField()),
                ('reply_subject', models.TextField()),
                ('sender', models.EmailField(max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
