# Generated by Django 6.0.2 on 2026-05-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_workflowforhumanreview_agent_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowforhumanreview',
            name='agent_id',
        ),
        migrations.AddField(
            model_name='workflowforhumanreview',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
