# Generated by Django 6.0.2 on 2026-06-04 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0005_workflowforhumanreview_agent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowforhumanreview',
            name='human_choice',
            field=models.CharField(choices=[('pending', 'Pending'), ('accept', 'Accept'), ('reject', 'Reject'), ('manual_reply', 'Manual Reply')], default='pending', max_length=100),
        ),
    ]
