# Generated by Django 6.0.2 on 2026-06-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0006_alter_workflowforhumanreview_human_choice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflowforhumanreview',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='workflowforhumanreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
