# Generated by Django 6.0.2 on 2026-06-11 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0008_workflowexecution'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflowforhumanreview',
            options={'ordering': ['-created_at']},
        ),
    ]
