# Generated by Django 6.0.2 on 2026-06-12 07:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0010_builtinagent_capabilities_builtinagent_tools'),
        ('workflows', '0010_emailexecutionresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_id', models.CharField(db_index=True, max_length=255)),
                ('thread_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sender', models.EmailField(max_length=254)),
                ('recipient', models.EmailField(blank=True, max_length=254, null=True)),
                ('original_subject', models.TextField(blank=True, null=True)),
                ('original_body', models.TextField(blank=True, null=True)),
                ('detected_intent', models.CharField(blank=True, max_length=255, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('reply_subject', models.TextField(blank=True, null=True)),
                ('reply_body', models.TextField(blank=True, null=True)),
                ('result', models.CharField(choices=[('AUTO_RESOLVED', 'Auto Resolved'), ('HUMAN_REVIEW', 'Human Review'), ('SKIPPED', 'Skipped'), ('FAILED', 'Failed')], max_length=30)),
                ('review_reason', models.TextField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_executions', to='agent.agent')),
                ('workflow_execution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_execution', to='workflows.workflowexecution')),
            ],
            options={
                'ordering': ['-processed_at'],
                'indexes': [models.Index(fields=['email_id'], name='workflows_e_email_i_c80205_idx'), models.Index(fields=['result'], name='workflows_e_result_44f31b_idx'), models.Index(fields=['processed_at'], name='workflows_e_process_93ed44_idx')],
            },
        ),
    ]
