# Generated by Django 6.0.2 on 2026-06-12 09:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0011_emailexecution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailexecution',
            name='email_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='emailexecution',
            name='result',
            field=models.CharField(blank=True, choices=[('AUTO_RESOLVED', 'Auto Resolved'), ('HUMAN_REVIEW', 'Human Review'), ('SKIPPED', 'Skipped'), ('FAILED', 'Failed')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='emailexecution',
            name='sender',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=500)),
                ('mime_type', models.CharField(max_length=255)),
                ('s3_key', models.CharField(max_length=1000)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('processing_status', models.CharField(choices=[('PROCESSED', 'Processed'), ('UNSUPPORTED', 'Unsupported'), ('FAILED', 'Failed')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='workflows.emailexecution')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
