# Generated by Django 6.0.2 on 2026-06-13 12:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0012_alter_emailexecution_email_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAIUsageSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_calls', models.IntegerField()),
                ('intent_analysis_calls', models.IntegerField()),
                ('reply_generation_calls', models.IntegerField()),
                ('embedding_calls', models.IntegerField()),
                ('openrouter_calls', models.IntegerField()),
                ('gemini_calls', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=100)),
                ('operation', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workflow_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage_logs', to='workflows.workflowexecution')),
            ],
        ),
    ]
