# Generated by Django 6.0.2 on 2026-06-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0016_meetingsummaryexecution_summary_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeexecution',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resumeexecution',
            name='file_path',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='resumeexecution',
            name='file_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='resumeexecution',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='resumeexecution',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='workflowexecution',
            name='status',
            field=models.CharField(choices=[('RUNNING', 'RUNNING'), ('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED'), ('PENDING', 'PENDING')], default='RUNNING', max_length=20),
        ),
    ]
