# Generated by Django 6.0.2 on 2026-05-20 05:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_agent_agent_schema_builtinagent_input_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentDocuments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document', models.FileField(upload_to='agent-documents/')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='agent.agent')),
            ],
        ),
    ]
