# Generated by Django 6.0.2 on 2026-05-21 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_agentdocuments'),
    ]

    operations = [
        migrations.CreateModel(
            name='S3MarketIntelligenceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s3_key', models.CharField(max_length=550)),
                ('s3_url', models.URLField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_intelligence_reports', to='agent.agent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
