# Generated by Django 6.0.2 on 2026-05-22 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_s3marketintelligencereport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentExecution',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
                ('current_step', models.CharField(blank=True, max_length=255, null=True)),
                ('market_research', models.TextField(blank=True, null=True)),
                ('competitors', models.TextField(blank=True, null=True)),
                ('trends', models.TextField(blank=True, null=True)),
                ('sentiment', models.TextField(blank=True, null=True)),
                ('swot', models.TextField(blank=True, null=True)),
                ('final_report', models.TextField(blank=True, null=True)),
                ('report_path', models.TextField(blank=True, null=True)),
                ('s3_url', models.TextField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exicution_instances', to='agent.agent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
