# Generated by Django 6.0.2 on 2026-05-22 11:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0006_agentexecution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentexecution',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
