# Generated by Django 6.0.2 on 2026-05-23 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0007_alter_agentexecution_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentexecution',
            name='scraped_data_from_competitor_websites',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentexecution',
            name='scraped_data_from_compony_website',
            field=models.TextField(blank=True, null=True),
        ),
    ]
