# Generated by Django 6.0.2 on 2026-05-19 05:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='agent',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_agent_per_user'),
        ),
    ]
