# Generated by Django 6.0.2 on 2026-03-14 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentaction',
            name='agent',
        ),
        migrations.RemoveIndex(
            model_name='agentrun',
            name='agent_agent_agent_i_688343_idx',
        ),
        migrations.RemoveField(
            model_name='agentstep',
            name='run',
        ),
        migrations.RemoveIndex(
            model_name='agenttrigger',
            name='agent_agent_trigger_3d91d3_idx',
        ),
        migrations.RemoveField(
            model_name='toolconnection',
            name='user',
        ),
        migrations.RemoveIndex(
            model_name='agent',
            name='agent_agent_user_id_2f5d4e_idx',
        ),
        migrations.AddField(
            model_name='agent',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='AgentAction',
        ),
        migrations.RemoveField(
            model_name='agentrun',
            name='agent',
        ),
        migrations.DeleteModel(
            name='AgentStep',
        ),
        migrations.RemoveField(
            model_name='agenttrigger',
            name='agent',
        ),
        migrations.DeleteModel(
            name='ToolConnection',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='goal_prompt',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='llm_model',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='status',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='temperature',
        ),
        migrations.DeleteModel(
            name='AgentRun',
        ),
        migrations.DeleteModel(
            name='AgentTrigger',
        ),
    ]
