# Generated by Django 6.0.2 on 2026-05-20 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_agent_unique_agent_per_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='agent_schema',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='builtinagent',
            name='input_schema',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
