# Generated by Django 6.0.2 on 2026-06-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0008_agentexecution_scraped_data_from_competitor_websites_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='builtinagent',
            name='required_integrations',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
