# Generated by Django 6.0.2 on 2026-06-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0009_builtinagent_required_integrations'),
    ]

    operations = [
        migrations.AddField(
            model_name='builtinagent',
            name='capabilities',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='builtinagent',
            name='tools',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
