# Generated by Django 6.0.2 on 2026-06-21 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0010_builtinagent_capabilities_builtinagent_tools'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentdocuments',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='agentdocuments',
            name='original_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agentdocuments',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, null=True),
        ),
    ]
